Setup pipeline build in this repo

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -26,7 +26,7 @@ jobs:
         id: versions
         env:
           LAMBDA_COMPONENTS: "biocache-index-management"
-          DOCKER_COMPONENTS: "pipeline-batch-runner"
+          DOCKER_COMPONENTS: "pipelines"
         run: |
           ALL_VERSIONS='{}'
           # Terraform
@@ -139,141 +139,141 @@ jobs:
 #          tag: terraform-v${{ needs.get-versions.outputs.terraform_version }}
 #          artifacts: "terraform/terraform-${{ needs.get-versions.outputs.terraform_version }}.tar.gz"
 
-#  build-and-push-docker-images:
-#    runs-on: [ self-hosted ]
-#    needs: get-versions
-#    if: needs.get-versions.outputs.docker_build_matrix != '[]'
-#    permissions:
-#      contents: write
-#      actions: write
-#    strategy:
-#      fail-fast: false
-#      matrix:
-#        docker: ${{ fromJSON(needs.get-versions.outputs.docker_build_matrix) }}
-#    steps:
-#      - uses: actions/checkout@v4
-#        with:
-#          token: ${{ secrets.GITHUB_TOKEN }}
-#
-#      - name: Login to AWS
-#        uses: aws-actions/configure-aws-credentials@v4
-#        with:
-#          aws-access-key-id: ${{ secrets.AWS_PERSONAL_ACCESS_KEY }}
-#          aws-secret-access-key: ${{ secrets.AWS_PERSONAL_SECRET }}
-#          aws-region: ${{ secrets.AWS_REGION }}
-#          role-to-assume: ${{ secrets.DEV_DEPLOYMENT_ROLE_ARN }}
-#          role-skip-session-tagging: true
-#
-#      - name: Docker login to Amazon ECR
-#        env:
-#          AWS_REGION: ${{ secrets.AWS_REGION }}
-#        run: |
-#          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
-#            | docker login --username AWS --password-stdin 632683202044.dkr.ecr.eu-west-1.amazonaws.com
-#
-#      - name: Login to AWS
-#        uses: aws-actions/configure-aws-credentials@v4
-#        with:
-#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-#          aws-region: ${{ secrets.AWS_REGION }}
-#          role-to-assume: ${{ secrets.AWS_SHARED_INFRA_ROLE_ARN }}
-#
-#      - name: Docker login to Amazon ECR
-#        env:
-#          AWS_REGION: ${{ secrets.AWS_REGION }}
-#        run: |
-#          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
-#            | docker login --username AWS --password-stdin ${{ secrets.ECR_REPO }}
-#
-#      - name: Set up QEMU
-#        uses: docker/setup-qemu-action@v3
-#
-#      - name: Set up Docker Buildx
-#        uses: docker/setup-buildx-action@v3
-#        with:
-#          cache-binary: false
-#          platforms: linux/amd64,linux/arm64
-#          # Should probably make this our own docker pull-through
-#          buildkitd-config-inline: |
-#            [registry."docker.io"]
-#              mirrors = ["632683202044.dkr.ecr.eu-west-1.amazonaws.com/docker-hub"]
-#      #          driver-opts: |
-#      #            image=moby/buildkit:buildx-stable-1
-#
-#      - name: Cache
-#        uses: actions/cache@v4
-#        id: cache
-#        with:
-#          path: |
-#            var-cache-yum
-#            maven-cache
-#          key: cache-docker-${{ matrix.docker.component }}-${{ hashFiles('./docker/${{ matrix.docker.component }}') }}
-#          restore-keys: |
-#            cache-docker-${{ matrix.docker.component }}
-#
-#      - name: inject cache into docker
-#        uses: reproducible-containers/buildkit-cache-dance@v3.1.0
-#        with:
-#          cache-map: |
-#            {
-#              "var-cache-yum": "/var/cache/yum",
-#              "maven-cache": "/root/.m2/repository"
-#            }
-#          skip-extraction: ${{ steps.cache.outputs.cache-hit }}
-#
-#      - name: Build and push docker images
-#        working-directory: ./docker/${{ matrix.docker.name }}
-#        env:
-#          SOURCE_DATE_EPOCH: 0
-#          COMPONENT: ${{ matrix.docker.name }}
-#          VERSION: ${{ matrix.docker.version }}
-#        run: |
-#          set -e -o pipefail
-#
-#          arch=$(uname -m)
-#          if [ "${arch}" == "aarch64" ]; then
-#            echo "Building for arm64"
-#            export BUILDPLATFORM="linux/arm64"
-#          elif [ "${arch}" == "x86_64" ]; then
-#            echo "Building for amd64"
-#            export BUILDPLATFORM="linux/amd64"
-#          else
-#            echo "Cannot build for unknown architecture: ${arch}"
-#            exit 1
-#          fi
-#
-#          echo " Releasing ${COMPONENT} version ${VERSION}"
-#          export TAG=${VERSION}
-#          export DOCKER_REPO="${{ secrets.ECR_REPO }}"
-#          export GIT_TAG="docker-${COMPONENT}-v${VERSION}"
-#
-#          export CACHE_TAG="cache-github"
-#
-#          docker buildx build --push \
-#            ${COMPONENT} \
-#            --set="*.args.BUILDPLATFORM=${BUILDPLATFORM}" \
-#            --set="${COMPONENT}.platform=linux/amd64,linux/arm64" \
-#            --set="${COMPONENT}.labels.maintainer=support.natuurdata@inbo.be" \
-#            --set="${COMPONENT}.labels.build_date=$(date +'%Y-%m-%dT%H:%M:%S')" \
-#            --set="${COMPONENT}.labels.build_url=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
-#            --set="${COMPONENT}.labels.git_tag=${GIT_TAG}" \
-#            --set="${COMPONENT}.labels.git_hash=${{ github.sha }}" \
-#            --set="custom-gradle-jdk11.cache-to=type=registry,ref=${DOCKER_REPO}/inbo-vbp-custom-gradle:jdk11-${CACHE_TAG},oci-mediatypes=true,image-manifest=true,mode=max" \
-#            --set="custom-gradle-jdk21.cache-to=type=registry,ref=${DOCKER_REPO}/inbo-vbp-custom-gradle:jdk21-${CACHE_TAG},oci-mediatypes=true,image-manifest=true,mode=max" \
-#            --set="custom-maven.cache-to=type=registry,ref=${DOCKER_REPO}/inbo-vbp-custom-maven:${CACHE_TAG},oci-mediatypes=true,image-manifest=true,mode=max" \
-#            --set="${COMPONENT}.cache-to=type=registry,ref=${DOCKER_REPO}/inbo-vbp-${COMPONENT}:${CACHE_TAG},oci-mediatypes=true,image-manifest=true,mode=max"
-#
-#      - name: Create tags
-#        uses: actions/github-script@v7
-#        with:
-#          script: |
-#            github.rest.git.createRef({
-#              owner: context.repo.owner,
-#              repo: context.repo.repo,
-#              ref: `refs/tags/${matrix.docker.name}-v${matrix.docker.version}`,
-#              sha: context.sha
-#            })
+  build-and-push-docker-images:
+    runs-on: [ self-hosted ]
+    needs: get-versions
+    if: needs.get-versions.outputs.docker_build_matrix != '[]'
+    permissions:
+      contents: write
+      actions: write
+    strategy:
+      fail-fast: false
+      matrix:
+        docker: ${{ fromJSON(needs.get-versions.outputs.docker_build_matrix) }}
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          token: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Login to AWS
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          aws-access-key-id: ${{ secrets.AWS_PERSONAL_ACCESS_KEY }}
+          aws-secret-access-key: ${{ secrets.AWS_PERSONAL_SECRET }}
+          aws-region: ${{ secrets.AWS_REGION }}
+          role-to-assume: ${{ secrets.DEV_DEPLOYMENT_ROLE_ARN }}
+          role-skip-session-tagging: true
+
+      - name: Docker login to Amazon ECR
+        env:
+          AWS_REGION: ${{ secrets.AWS_REGION }}
+        run: |
+          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
+            | docker login --username AWS --password-stdin 632683202044.dkr.ecr.eu-west-1.amazonaws.com
+
+      - name: Login to AWS
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: ${{ secrets.AWS_REGION }}
+          role-to-assume: ${{ secrets.AWS_SHARED_INFRA_ROLE_ARN }}
+
+      - name: Docker login to Amazon ECR
+        env:
+          AWS_REGION: ${{ secrets.AWS_REGION }}
+        run: |
+          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
+            | docker login --username AWS --password-stdin ${{ secrets.ECR_REPO }}
+
+      - name: Set up QEMU
+        uses: docker/setup-qemu-action@v3
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
+        with:
+          cache-binary: false
+          platforms: linux/amd64,linux/arm64
+          # Should probably make this our own docker pull-through
+          buildkitd-config-inline: |
+            [registry."docker.io"]
+              mirrors = ["632683202044.dkr.ecr.eu-west-1.amazonaws.com/docker-hub"]
+      #          driver-opts: |
+      #            image=moby/buildkit:buildx-stable-1
+
+      - name: Cache
+        uses: actions/cache@v4
+        id: cache
+        with:
+          path: |
+            var-cache-yum
+            maven-cache
+          key: cache-docker-${{ matrix.docker.component }}-${{ hashFiles('./docker/${{ matrix.docker.component }}') }}
+          restore-keys: |
+            cache-docker-${{ matrix.docker.component }}
+
+      - name: inject cache into docker
+        uses: reproducible-containers/buildkit-cache-dance@v3.1.0
+        with:
+          cache-map: |
+            {
+              "var-cache-yum": "/var/cache/yum",
+              "maven-cache": "/root/.m2/repository"
+            }
+          skip-extraction: ${{ steps.cache.outputs.cache-hit }}
+
+      - name: Build and push docker images
+        working-directory: ./docker/${{ matrix.docker.name }}
+        env:
+          SOURCE_DATE_EPOCH: 0
+          COMPONENT: ${{ matrix.docker.name }}
+          VERSION: ${{ matrix.docker.version }}
+        run: |
+          set -e -o pipefail
+
+          arch=$(uname -m)
+          if [ "${arch}" == "aarch64" ]; then
+            echo "Building for arm64"
+            export BUILDPLATFORM="linux/arm64"
+          elif [ "${arch}" == "x86_64" ]; then
+            echo "Building for amd64"
+            export BUILDPLATFORM="linux/amd64"
+          else
+            echo "Cannot build for unknown architecture: ${arch}"
+            exit 1
+          fi
+
+          echo " Releasing ${COMPONENT} version ${VERSION}"
+          export TAG=${VERSION}
+          export DOCKER_REPO="${{ secrets.ECR_REPO }}"
+          export GIT_TAG="docker-${COMPONENT}-v${VERSION}"
+
+          export CACHE_TAG="cache-github"
+
+          docker buildx build --push \
+            ${COMPONENT} \
+            --set="*.args.BUILDPLATFORM=${BUILDPLATFORM}" \
+            --set="${COMPONENT}.platform=linux/amd64,linux/arm64" \
+            --set="${COMPONENT}.labels.maintainer=support.natuurdata@inbo.be" \
+            --set="${COMPONENT}.labels.build_date=$(date +'%Y-%m-%dT%H:%M:%S')" \
+            --set="${COMPONENT}.labels.build_url=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
+            --set="${COMPONENT}.labels.git_tag=${GIT_TAG}" \
+            --set="${COMPONENT}.labels.git_hash=${{ github.sha }}" \
+            --set="custom-gradle-jdk11.cache-to=type=registry,ref=${DOCKER_REPO}/inbo-vbp-custom-gradle:jdk11-${CACHE_TAG},oci-mediatypes=true,image-manifest=true,mode=max" \
+            --set="custom-gradle-jdk21.cache-to=type=registry,ref=${DOCKER_REPO}/inbo-vbp-custom-gradle:jdk21-${CACHE_TAG},oci-mediatypes=true,image-manifest=true,mode=max" \
+            --set="custom-maven.cache-to=type=registry,ref=${DOCKER_REPO}/inbo-vbp-custom-maven:${CACHE_TAG},oci-mediatypes=true,image-manifest=true,mode=max" \
+            --set="${COMPONENT}.cache-to=type=registry,ref=${DOCKER_REPO}/inbo-vbp-${COMPONENT}:${CACHE_TAG},oci-mediatypes=true,image-manifest=true,mode=max"
+
+      - name: Create tags
+        uses: actions/github-script@v7
+        with:
+          script: |
+            github.rest.git.createRef({
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              ref: `refs/tags/${matrix.docker.name}-v${matrix.docker.version}`,
+              sha: context.sha
+            })
 
   build-and-release-frontend:
     runs-on: [ self-hosted ]
@@ -358,7 +358,7 @@ jobs:
       - build-and-release-terraform
       - build-and-release-frontend
       - build-and-release-lambdas
-#      - build-and-push-docker-images
+      - build-and-push-docker-images
     # Only run if no failures or cancellations and at least one was not skipped
     if: |
       always()
